with variable lengthscale:


In [2]:
import torch
x = torch.tensor([xi-xj for xi in range(10) for xj in range(10)])
x.view(10, 10)

tensor([[ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9],
        [ 1,  0, -1, -2, -3, -4, -5, -6, -7, -8],
        [ 2,  1,  0, -1, -2, -3, -4, -5, -6, -7],
        [ 3,  2,  1,  0, -1, -2, -3, -4, -5, -6],
        [ 4,  3,  2,  1,  0, -1, -2, -3, -4, -5],
        [ 5,  4,  3,  2,  1,  0, -1, -2, -3, -4],
        [ 6,  5,  4,  3,  2,  1,  0, -1, -2, -3],
        [ 7,  6,  5,  4,  3,  2,  1,  0, -1, -2],
        [ 8,  7,  6,  5,  4,  3,  2,  1,  0, -1],
        [ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0]])

In [12]:
import numpy as np
import matplotlib.pyplot as plt

test_nodes = np.load("dataset\\bjair\\NP\\test_nodes.npy")
test_nodes1 = np.load("dataset\\bjair\\NP\\test_nodes1.npy")
test_nodes2 = np.load("dataset\\bjair\\NP\\test_nodes2.npy")
test_nodes3 = np.load("dataset\\bjair\\NP\\test_nodes3.npy")
test_nodes4 = np.load("dataset\\bjair\\NP\\test_nodes4.npy")
test_nodes5 = np.load("dataset\\bjair\\NP\\test_nodes5.npy")


In [13]:
print(test_nodes)
print(test_nodes1)
print(test_nodes2)
print(test_nodes3)
print(test_nodes4)
print(test_nodes5)

[ 0  1  3  4  7  8 13 14 18 29 31 34]
[ 0  3  4 11 14 20 21 24 25 27 28 32]
[ 0  2  9 12 13 16 19 23 27 30 31 34]
[ 1  4  7  8  9 12 15 20 23 24 27 33]
[ 2  3  6  8  9 10 16 19 21 27 29 30]
[ 1  2  7 11 13 15 17 20 24 26 29 30]


In [11]:
a = np.random.choice([i for i in range(35)], 12, replace=False).astype("int64")
a.sort()
np.save("dataset\\bjair\\NP\\test_nodes1.npy", a)